name: WOA-Deployer with SuperJMN Deployer Upstreaming

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  upstream-and-save:
    runs-on: windows-latest

    steps:
    - name: Checkout WOA-Deployer
      uses: actions/checkout@v2
      with:
        repository: mmrecdev/WOA-Deployer
        path: WOA-Deployer

    - name: Checkout SuperJMN Deployer
      uses: actions/checkout@v2
      with:
        repository: SuperJMN/Deployer
        path: SuperJMN-Deployer

    - name: Upstream WOA-Deployer
      run: |
        cd WOA-Deployer
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add upstream https://github.com/original-woa-deployer-repo/WOA-Deployer.git
        git fetch upstream
        git merge upstream/main --allow-unrelated-histories
        git push origin main

    - name: Upstream SuperJMN Deployer
      run: |
        cd SuperJMN-Deployer
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add upstream https://github.com/original-superjmn-deployer-repo/Deployer.git
        git fetch upstream
        git merge upstream/main --allow-unrelated-histories
        git push origin main

    - name: Archive Repositories
      uses: actions/upload-artifact@v2
      with:
        name: upstreamed-repositories
        path: |
          WOA-Deployer
          SuperJMN-Deployer

    - name: Notify Success
      if: success()
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            body: "Upstreaming completed successfully!"
          })

    - name: Notify Failure
      if: failure()
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            body: "Upstreaming failed. Please check the logs for details."
          })
