name: WOA-Deployer with SuperJMN Deployer Upstreaming

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      custom_branch:
        description: 'Custom branch to upstream'
        required: false
        default: 'main'
      force_push:
        description: 'Force push to origin'
        type: boolean
        required: false
        default: false

jobs:
  upstream-and-save:
    runs-on: windows-latest

    steps:
    - name: Checkout WOA-Deployer
      uses: actions/checkout@v2
      with:
        repository: mmrecdev/WOA-Deployer
        path: WOA-Deployer
        fetch-depth: 0

    - name: Checkout SuperJMN Deployer
      uses: actions/checkout@v2
      with:
        repository: SuperJMN/Deployer
        path: SuperJMN-Deployer
        fetch-depth: 0

    - name: Set Git Config
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com

    - name: Upstream WOA-Deployer
      run: |
        cd WOA-Deployer
        git remote add upstream https://github.com/mmrecdev/WOA-Deployer.git
        git fetch upstream
        git checkout ${{ github.event.inputs.custom_branch || 'main' }}
        git merge -X theirs --no-commit --no-ff upstream/${{ github.event.inputs.custom_branch || 'main' }}
        git commit -m "Merge upstream changes" || echo "No changes to commit"
        git push origin ${{ github.event.inputs.custom_branch || 'main' }} ${{ github.event.inputs.force_push && '--force' || '' }}

    - name: Upstream SuperJMN Deployer
      run: |
        cd SuperJMN-Deployer
        git remote add upstream https://github.com/SuperJMN/Deployer.git
        git fetch upstream
        git checkout ${{ github.event.inputs.custom_branch || 'main' }}
        git merge -X theirs --no-commit --no-ff upstream/${{ github.event.inputs.custom_branch || 'main' }}
        git commit -m "Merge upstream changes" || echo "No changes to commit"
        git push origin ${{ github.event.inputs.custom_branch || 'main' }} ${{ github.event.inputs.force_push && '--force' || '' }}

    - name: Zip Repositories
      run: |
        7z a -tzip WOA-Deployer.zip ./WOA-Deployer/*
        7z a -tzip SuperJMN-Deployer.zip ./SuperJMN-Deployer/*

    - name: Upload Zipped Repositories
      uses: actions/upload-artifact@v2
      with:
        name: upstreamed-repositories
        path: |
          WOA-Deployer.zip
          SuperJMN-Deployer.zip

    - name: Notify Success
      if: success()
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Upstreaming completed successfully! Branch: ${{ github.event.inputs.custom_branch || 'main' }}, Force push: ${{ github.event.inputs.force_push }}"
          })

    - name: Notify Failure
      if: failure()
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Upstreaming failed. Please check the logs for details. Branch: ${{ github.event.inputs.custom_branch || 'main' }}, Force push: ${{ github.event.inputs.force_push }}"
          })
