name: WOA-Deployer with SuperJMN Deployer Upstreaming

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      custom_branch:
        description: 'Custom branch to upstream'
        required: false
        default: 'main'
      force_push:
        description: 'Force push to origin'
        type: boolean
        required: false
        default: false

jobs:
  upstream-and-save:
    runs-on: windows-latest

    steps:
    - name: Create Working Directories
      run: |
        mkdir WOA-Deployer
        mkdir SuperJMN-Deployer

    - name: Clone WOA-Deployer
      run: |
        git clone https://github.com/mmrecdev/WOA-Deployer.git WOA-Deployer
        cd WOA-Deployer
        git checkout ${{ github.event.inputs.custom_branch || 'main' }}

    - name: Clone SuperJMN Deployer
      run: |
        git clone https://github.com/SuperJMN/Deployer.git SuperJMN-Deployer
        cd SuperJMN-Deployer
        git checkout ${{ github.event.inputs.custom_branch || 'main' }}

    - name: Set Git Config
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com

    - name: Upstream WOA-Deployer with SuperJMN Deployer
      run: |
        cd WOA-Deployer
        git remote add superjmn ../SuperJMN-Deployer
        git fetch superjmn
        git rev-list --no-merges HEAD..superjmn/${{ github.event.inputs.custom_branch || 'main' }} | while read commit; do
          git cherry-pick --strategy=recursive -X theirs $commit || true
        done

    - name: Upstream SuperJMN Deployer with WOA-Deployer
      run: |
        cd SuperJMN-Deployer
        git remote add woa ../WOA-Deployer
        git fetch woa
        git rev-list --no-merges HEAD..woa/${{ github.event.inputs.custom_branch || 'main' }} | while read commit; do
          git cherry-pick --strategy=recursive -X theirs $commit || true
        done

    - name: Zip Repositories
      run: |
        7z a -tzip WOA-Deployer.zip ./WOA-Deployer/*
        7z a -tzip SuperJMN-Deployer.zip ./SuperJMN-Deployer/*

    - name: Upload Zipped Repositories
      uses: actions/upload-artifact@v2
      with:
        name: upstreamed-repositories
        path: |
          WOA-Deployer.zip
          SuperJMN-Deployer.zip

    - name: Notify Success
      if: success()
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Upstreaming completed successfully! Branch: ${{ github.event.inputs.custom_branch || 'main' }}"
          })

    - name: Notify Failure
      if: failure()
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Upstreaming failed. Please check the logs for details. Branch: ${{ github.event.inputs.custom_branch || 'main' }}"
          })
